name       : python-intervaltree
version    : 3.1.0
release    : 3
source     :
    - https://github.com/chaimleib/intervaltree/archive/3.1.0.tar.gz : d6c1269a7875c98146b0aedbcc1afd7ca8f9f1e8f59c412c853f1173bc6a52b1
homepage   : https://github.com/chaimleib/intervaltree
license    : Apache-2.0
component  : programming.python
summary    : A mutable, self-balancing interval tree. Queries may be by point, by range overlap, or by range containment
description: |
    A mutable, self-balancing interval tree. Queries may be by point, by range overlap, or by range containment.
builddeps  :
    - python-pytest
    - python-sortedcontainers
rundeps    :
    - python-sortedcontainers
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    pytest3 -v py3build/test
