name       : python-intervaltree
version    : 3.0.2
release    : 1
source     :
    - https://github.com/chaimleib/intervaltree/archive/3.0.2.tar.gz : e8ab75b66077f2e5fb85ac56cb6df834689edb048d38601d53d8867cce3b77d1
homepage   : https://github.com/chaimleib/intervaltree
license    : Apache-2.0
component  : programming.python
summary    : A mutable, self-balancing interval tree. Queries may be by point, by range overlap, or by range containment
description: |
    A mutable, self-balancing interval tree. Queries may be by point, by range overlap, or by range containment.
rundeps    :
    - python-sortedcontainers
build      : |
    %python3_setup
install    : |
    %python3_install
